const router = require('express').Router();
const auth = require('../middleware/auth');
const c = require('../controllers/projectController');
router.get('/', auth, c.getAll);
router.post('/', auth, c.create);
router.get('/:id', auth, c.getOne);
router.put('/:id', auth, c.update);
router.delete('/:id', auth, c.remove);
router.post('/:id/members', auth, c.addMember);
router.delete('/:id/members/:userId', auth, c.removeMember);
module.exports = router;